spring.application.name=PROGETTO_SETTIMANALE_S17
# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/progetto_s17
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate
spring.jpa.hibernate.ddl-auto=update